version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb

  web:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb

  site:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
